### PR TITLE
tests: added Karma headless tests + distributable for browsers

### PR DESCRIPTION
**Pull request by Alex-Werner**
### Issue being fixed or implemented  

This PR adds distributable for browsers (UMD) and unpkg helper to allow users to use DPNS Client from browsers. 
Using this distributable build, we also uses it to run some specific functional test by karma. 

### What was done  

- Added Karma / Webpack dependencies
- Configured Karma, Webpack, Travis and NPM (scripts)
- Build a distributable (UMD) on travis run (.gitignore folder)  
- Documentation for unpkg usage 

### How Has This Been Tested?

Added additional test for browsers. 

### Notes  

gRPC still giving us some headaches here :'(

### Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation

Requirements (JIRA): 
- [X] scripts in package.json (unpkg, main)
- [X] setup/configure webpack, karma
- [X] configure travis build

### CODE REVIEW

**Review by shumkov — CHANGES_REQUESTED** [review]
@Alex-Werner we need to require `bootstrap.karma` before tests.

**Comment by Alex-Werner** [comment]
@shumkov I would like to revert commit 24ea6b2, indeed, while I agree we should run test in unit, this distributable test intend to just perform some call to the real network in a real-usage context. 
It's basically an e2e/functional test, except our current functional test relies on generate new block. 
Instead, this test (distributable) will just perform this : 

1) it should initialize
2) it should resolve
3) it should search

It could do registering too, but this test is done by DashJS already, not sure if it wouldn't be too much here (because then you need to manage funding the keys each evonet redeploy).

**Review by shumkov — APPROVED** [review]
utACK

**Comment by Alex-Werner** [comment]
Nice ! I did hate those rewiremock errors a lot :) 

We do not lose some coverage with that one ? I mean on the DPNSClient side of things.

**Comment by shumkov** [comment]
@Alex-Werner we removed a test for DPSNClient constructor but it's ok.

**Pull request merged**
